name: Unzip
on: workflow_dispatch
jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          unzip -o "*.zip" || true
          find . -name "*.zip" -exec unzip -o {} \;
      - run: rm -rf *.zip project-bolt* __MACOSX
      - run: |
          git config user.name "bot"
          git config user.email "bot@bot.com"
          git add .
          git commit -m "extracted" || true
          git push
